export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_RELOAD = "LOGIN_RELOAD";
export const LOGIN_SUCCEED = "LOGIN_SUCCEED";

export const AUTH_FAIL =  "AUTH_FAIL";
export const AUTH_LOADING =  "AUTH_LOADING";
export const AUTH_RELOAD =  "AUTH_RELOAD";
export const AUTH_SUCCEED = "AUTH_SUCCEED";


export const RESET_STATE_FAIL = "RESET_STATE_FAIL";
export const RESET_STATE_LOADING = "RESET_STATE_LOADING";
export const RESET_STATE_RELOAD = "RESET_STATE_RELOAD";
export const RESET_STATE_SUCCEED = "RESET_STATE_SUCCEED";


export const GET_TICKER_FAIL = "GET_TICKER_FAIL";
export const GET_TICKER_LOADING = "GET_TICKER_LOADING";
export const GET_TICKER_RELOAD = "GET_TICKER_RELOAD";
export const GET_TICKER_SUCCEED = "GET_TICKER_SUCCEED";

