export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_RELOAD = "LOGIN_RELOAD";
export const LOGIN_SUCCEED = "LOGIN_SUCCEED";

export const AUTH_FAIL =  "AUTH_FAIL";
export const AUTH_LOADING =  "AUTH_LOADING";
export const AUTH_RELOAD =  "AUTH_RELOAD";
export const AUTH_SUCCEED = "AUTH_SUCCEED";

export const RESET_STATE_FAIL = "RESET_STATE_FAIL";
export const RESET_STATE_LOADING = "RESET_STATE_LOADING";
export const RESET_STATE_RELOAD = "RESET_STATE_RELOAD";
export const RESET_STATE_SUCCEED = "RESET_STATE_SUCCEED";

export const ADD_EVENT_FAIL = "ADD_EVENT_FAIL";
export const ADD_EVENT_LOADING = "ADD_EVENT_LOADING";
export const ADD_EVENT_RELOAD = "ADD_EVENT_RELOAD";
export const ADD_EVENT_SUCCEED = "ADD_EVENT_SUCCEED";

export const LIST_EVENT_FAIL = "LIST_EVENT_FAIL";
export const LIST_EVENT_LOADING = "LIST_EVENT_LOADING";
export const LIST_EVENT_RELOAD = "LIST_EVENT_RELOAD";
export const LIST_EVENT_SUCCEED = "LIST_EVENT_SUCCEED";