export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_RELOAD = "LOGIN_RELOAD";
export const LOGIN_SUCCEED = "LOGIN_SUCCEED";

export const GET_SERVER_FAIL = "GET_SERVER_FAIL";
export const GET_SERVER_LOADING = "GET_SERVER_LOADING";
export const GET_SERVER_RELOAD = "GET_SERVER_RELOAD";
export const GET_SERVER_SUCCEED = "GET_SERVER_SUCCEED";

export const SOCKET_FAIL = "SOCKET_FAIL";
export const SOCKET_LOADING = "SOCKET_LOADING";
export const SOCKET_RELOAD = "SOCKET_RELOAD";
export const SOCKET_SUCCEED = "SOCKET_SUCCEED";

export const GET_BANNER_FAIL = "GET_BANNER_FAIL";
export const GET_BANNER_LOADING = "GET_BANNER_LOADING";
export const GET_BANNER_RELOAD = "GET_BANNER_RELOAD";
export const GET_BANNER_SUCCEED = "GET_BANNER_SUCCEED";


export const RESET_STATE_FAIL = "RESET_STATE_FAIL";
export const RESET_STATE_LOADING = "RESET_STATE_LOADING";
export const RESET_STATE_RELOAD = "RESET_STATE_RELOAD";
export const RESET_STATE_SUCCEED = "RESET_STATE_SUCCEED";


export const GET_TICKER_FAIL = "GET_TICKER_FAIL";
export const GET_TICKER_LOADING = "GET_TICKER_LOADING";
export const GET_TICKER_RELOAD = "GET_TICKER_RELOAD";
export const GET_TICKER_SUCCEED = "GET_TICKER_SUCCEED";

